version: "3"

services:

  proxy:
    image: "nginx"
    container_name: "nginx-proxy"
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      load-balancer:
          ipv4_address: 172.20.0.20
    restart: always


  unicorn:
    build: ./
    # image: "containous/whoami"
    networks:
      - load-balancer
    restart: always
    labels:
      - "autoheal=true"
      - "autoheal.stop.timeout=15"

  autoheal:
    image: "willfarrell/autoheal"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always

networks:
  load-balancer:
    ipam:
      config:
        - subnet: 172.20.0.0/24
