AWSTemplateFormatVersion: 2010-09-09
Description: MySQL database instance

Parameters:

  Network:
    Type: String
    Description: Network stack name

  DBName:
    Type: String
    Default: worldskills
    Description: Database name

  DBUser:
    Type: String
    Default: root
    Description: Database user

  EnvironmentType:
    Type: String
    Description: Environment type (Production or Test)
    AllowedValues:
      - Prod
      - Test

  SubnetPrefix:
    Type: String
    Description: Database security (Public or Private)
    AllowedValues:
      - Public
      - Private

  Version:
    Type: String
    Description: Application version
    Default: Default

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    -
      Label:
        default: "Stack Association"
      Parameters:
        - Network
    -
      Label:
        default: "Environment Properties"
      Parameters:
        - EnvironmentType
    -
      Label:
        default: "Database Properties"
      Parameters:
        - SubnetPrefix
        - DBName
        - DBUser
        - Version

Conditions:
  CreateResourcesProd: !Equals [!Ref EnvironmentType, Prod]
  CreateResourcesTest: !Equals [!Ref EnvironmentType, Test]

Resources:
  MyRDSInstanceSecret:
    Condition: CreateResourcesProd
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: AWS RDS MySQL ABCZ Production Instance Access
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${DBUser}"}'
        GenerateStringKey: 'password'
        PasswordLength: 20
        ExcludePunctuation: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentType}-mysql
    
  SecretRDSInstanceAttachment:
    Condition: CreateResourcesProd
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref MyRDSInstanceSecret
      TargetId: !Ref MySQLDBInstance
      TargetType: AWS::RDS::DBInstance

  PrivateDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: MysqlPrivateSubnetGroup
      SubnetIds:
        - Fn::ImportValue: !Sub ${Network}-${EnvironmentType}-${SubnetPrefix}-Subnet1
        - Fn::ImportValue: !Sub ${Network}-${EnvironmentType}-${SubnetPrefix}-Subnet2
      Tags:
        - Key: Name
          Value: MysqlPrivateSubnetGroup

  MySQLSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${EnvironmentType}-MySQL-SecurityGroup
      GroupDescription: !Sub ${EnvironmentType}-MySQL-SecurityGroup
      VpcId:
        Fn::ImportValue: !Sub ${Network}-${EnvironmentType}-MyVPC
      SecurityGroupIngress:
        -
          IpProtocol: "tcp"
          FromPort: "3306"
          ToPort: "3306"
          SourceSecurityGroupId:
            Fn::ImportValue: !Sub ${Network}-AppSecurityGroup
      Tags:
        - Key: Name
          Value: Database-SG

  MySQLDBInstance:
    Condition: CreateResourcesProd
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Properties:
      AllocatedStorage: 20
      # BackupRetentionPeriod: 0
      DBInstanceClass: db.t2.micro
      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: true
      DBInstanceIdentifier: !Join ['-',[!Ref EnvironmentType,!Ref Version,'mysql']]
      DBName: !Ref DBName
      VPCSecurityGroups:
        - !Ref MySQLSecurityGroup
      DBSubnetGroupName: !Ref PrivateDBSubnetGroup
      Engine: mysql
      EngineVersion: 8.0.15
      MasterUsername: !Sub '{{resolve:secretsmanager:${MyRDSInstanceSecret}:SecretString:username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${MyRDSInstanceSecret}:SecretString:password}}'
      MultiAZ: true
      PubliclyAccessible: false
      # StorageEncrypted: true
      # KmsKeyId: !Ref RDSKMSKey
      StorageType: gp2
      Tags:
        - Key: Name
          Value: !Join ['-',[!Ref EnvironmentType,!Ref Version,'mysql']]

  tMySQLDBInstance:
    Type: AWS::RDS::DBInstance
    Condition: CreateResourcesTest
    DeletionPolicy: Delete
    Properties:
      AllocatedStorage: 20
      # BackupRetentionPeriod: 0
      DBParameterGroupName: !Ref RDSDBParameterGroup
      DBInstanceClass: db.t2.micro
      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: true
      DBInstanceIdentifier: !Join ['-',[!Ref EnvironmentType,!Ref Version,'mysql']]
      DBName: !Ref DBName
      VPCSecurityGroups:
        - !Ref MySQLSecurityGroup
      DBSubnetGroupName: !Ref PrivateDBSubnetGroup
      Engine: mysql
      EngineVersion: 8.0.15
      MasterUsername: !Sub '{{resolve:secretsmanager:${tMyRDSInstanceSecret}:SecretString:username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${tMyRDSInstanceSecret}:SecretString:password}}'
      MultiAZ: false
      PubliclyAccessible: false
      # StorageEncrypted: true
      # KmsKeyId: !Ref RDSKMSKey
      StorageType: gp2
      Tags:
        - Key: Name
          Value: !Join ['-',[!Ref EnvironmentType,!Ref Version,'mysql']]

  RDSDBParameterGroup: 
    Condition: CreateResourcesTest
    Type: "AWS::RDS::DBParameterGroup"
    Properties: 
      Description: "CloudFormation Sample Parameter Group"
      Family: mysql8.0
      Parameters: 
        binlog_format: ROW
        binlog_checksum: NONE

  tMyRDSInstanceSecret:
    Condition: CreateResourcesTest
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: AWS RDS MySQL ABCZ Production Instance Access
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${DBUser}"}'
        GenerateStringKey: 'password'
        PasswordLength: 20
        ExcludePunctuation: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentType}-mysql
    
  tSecretRDSInstanceAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
        SecretId: !Ref tMyRDSInstanceSecret
        TargetId: !Ref tMySQLDBInstance
        TargetType: AWS::RDS::DBInstance

  # RDSKMSKey:
  #   Type: AWS::KMS::Key
  #   Properties:
  #     KeyPolicy:
  #       Version: 2012-10-17
  #       Id: RDS
  #       Statement:
  #         - Sid: Enable IAM User Permissions
  #           Effect: Allow
  #           Principal:
  #             AWS: !Join ['',['arn:aws:iam::',!Ref 'AWS::AccountId',':root']]
  #           Action: 'kms:*'
  #           Resource: '*'

Outputs:
  MySQLDBInstance:
    Condition: CreateResourcesProd
    Description: MySQLARN
    Value: !Ref MySQLDBInstance
    Export:
      Name: !Sub "${AWS::StackName}-MySQLDBInstance"

  MySQLDBInstanceEndpoint:
    Condition: CreateResourcesProd
    Description: 'MySQL Endpoint'
    Value: !GetAtt [MySQLDBInstance,Endpoint.Address]
    Export:
      Name: !Sub "${AWS::StackName}-MySQLDBInstanceEndpoint"

  MySQLSecurityGroup:
    Description: MySQL Security group
    Value: !Ref MySQLSecurityGroup
    Export:
      Name: !Sub ${AWS::StackName}-MySQLSecurityGroup
  
  MySQLSubnetGroup:
    Description: MySQL Subnet Group
    Value: !Ref PrivateDBSubnetGroup
    Export:
      Name: !Sub ${AWS::StackName}-MySQLSubnetGroup

  tMySQLDBInstance:
    Condition: CreateResourcesTest
    Description: MySQLARN
    Value: !Ref tMySQLDBInstance
    Export:
      Name: !Sub "${AWS::StackName}-MySQLDBInstance"

  tMySQLDBInstanceEndpoint:
    Condition: CreateResourcesTest
    Description: 'MySQL Endpoint'
    Value: !GetAtt [tMySQLDBInstance,Endpoint.Address]
    Export:
      Name: !Sub "${AWS::StackName}-MySQLDBInstanceEndpoint"

  RDSDBParameterGroup:
    Description: Parameter group ID
    Value: !Ref RDSDBParameterGroup
    Export:
      Name: !Sub "${AWS::StackName}-RDSDBParameterGroup"

