AWSTemplateFormatVersion: 2010-09-09
Description: MySQL database instance

Parameters:

  Network:
    Type: String
    Description: Network stack name

  DBName:
    Type: String
    Default: worldskills
    Description: Database name

  DBUser:
    Type: String
    Default: root
    Description: Database user

  DBPass:
    Type: String
    Description: Database password
    NoEcho: true

  EnvironmentType:
    Type: String
    Description: Environment type (Production or Test)
    AllowedValues:
      - Prod
      - Test

  SubnetPrefix:
    Type: String
    Description: Database security (Public or Private)
    AllowedValues:
      - Public
      - Private

  Version:
    Type: String
    Description: Application version
    Default: Default

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    -
      Label:
        default: "Stack Association"
      Parameters:
        - Network
    -
      Label:
        default: "Environment Properties"
      Parameters:
        - EnvironmentType
    -
      Label:
        default: "Database Properties"
      Parameters:
        - SubnetPrefix
        - DBName
        - DBUser
        - DBPass
        - Version

Resources:
  PrivateDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: MysqlPrivateSubnetGroup
      SubnetIds:
        - Fn::ImportValue: !Sub ${Network}-${EnvironmentType}-${SubnetPrefix}-Subnet1
        - Fn::ImportValue: !Sub ${Network}-${EnvironmentType}-${SubnetPrefix}-Subnet2
      Tags:
        - Key: Name
          Value: MysqlPrivateSubnetGroup

  MySQLSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${EnvironmentType}-MySQL-SecurityGroup
      GroupDescription: !Sub ${EnvironmentType}-MySQL-SecurityGroup
      VpcId:
        Fn::ImportValue: !Sub ${Network}-${EnvironmentType}-MyVPC
      SecurityGroupIngress:
        -
          IpProtocol: "tcp"
          FromPort: "3306"
          ToPort: "3306"
          SourceSecurityGroupId:
            Fn::ImportValue: !Sub ${Network}-AppSecurityGroup
      Tags:
        - Key: Name
          Value: Database-SG

  MySQLDBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Properties:
      AllocatedStorage: 20
      # BackupRetentionPeriod: 0
      DBInstanceClass: db.t2.micro
      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: true
      DBInstanceIdentifier: !Join ['-',[!Ref EnvironmentType,!Ref Version,'mysql']]
      DBName: !Ref DBName
      VPCSecurityGroups:
        - !Ref MySQLSecurityGroup
      DBSubnetGroupName: !Ref PrivateDBSubnetGroup
      Engine: mysql
      EngineVersion: 8.0.15
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPass
      MultiAZ: true
      PubliclyAccessible: false
      # StorageEncrypted: true
      # KmsKeyId: !Ref RDSKMSKey
      StorageType: gp2
      Tags:
        - Key: Name
          Value: !Join ['-',[!Ref EnvironmentType,!Ref Version,'mysql']]

  # RDSKMSKey:
  #   Type: AWS::KMS::Key
  #   Properties:
  #     KeyPolicy:
  #       Version: 2012-10-17
  #       Id: RDS
  #       Statement:
  #         - Sid: Enable IAM User Permissions
  #           Effect: Allow
  #           Principal:
  #             AWS: !Join ['',['arn:aws:iam::',!Ref 'AWS::AccountId',':root']]
  #           Action: 'kms:*'
  #           Resource: '*'

Outputs:
  MySQLDBInstance:
    Description: MySQLARN
    Value: !Ref MySQLDBInstance
    Export:
      Name: !Sub "${AWS::StackName}-MySQLDBInstance"

  MySQLDBInstanceEndpoint:
    Description: 'MySQL Endpoint'
    Value: !GetAtt [MySQLDBInstance,Endpoint.Address]
    Export:
      Name: !Sub "${AWS::StackName}-MySQLDBInstanceEndpoint"

  MySQLSecurityGroup:
    Description: MySQL Security group
    Value: !Ref MySQLSecurityGroup
    Export:
      Name: !Sub ${AWS::StackName}-MySQLSecurityGroup
  
  MySQLSubnetGroup:
    Description: MySQL Subnet Group
    Value: !Ref PrivateDBSubnetGroup
    Export:
      Name: !Sub ${AWS::StackName}-MySQLSubnetGroup

