AWSTemplateFormatVersion: 2010-09-09
Description: Lambda functions for atomatic refunds
  
Parameters:
  S3BucketName:
    Type: String
    Description: Bucket name (where lambda function is stored)
  
  S3FileLocation:
    Type: String
    Description: Lambda function path

  Team:
    Type: String
    Description: Gameday team ID

  GamedayAPIURL:
    Type: String
    Description: URL to send the refund codes

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    -
      Label:
        default: "Bucket properties"
      Parameters:
        - S3BucketName
        - S3FileLocation
    -
      Label:
        default: "Code properties"
      Parameters:
        - Team
        - GamedayAPIURL

Resources:
  LambdaRefund:
    Type: "AWS::Lambda::Function"
    Properties:
      Code: #required
        S3Bucket: !Ref S3BucketName
        S3Key: !Ref S3FileLocation
      Description: Lambda for automatic refunds
      Environment:
        Variables:
          LOG_LEVEL: 10
          gameday_properties: !Sub '{"team": "${Team}", "gamedayUrl": "${GamedayAPIURL}"}'
      FunctionName: refund-function
      Handler: lambda_function.lambda_handler #required
      Role: !GetAtt RefundLambdaRole.Arn #required
      Runtime: python3.8 #required

  RefundLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 
                  - cloudwatch:*
                  - s3:*
                  - logs:*
                Resource: '*'
      RoleName: refund-lambda-role
  
Outputs:
  RefundLambda:
    Value: !Ref LambdaRefund
    Export:
      Name: !Sub ${AWS::StackName}-RefundLambda
  
  RefundLambdaRole:
    Value: !Ref RefundLambdaRole
    Export:
      Name: !Sub ${AWS::StackName}-RefundLambdaRole